name: SSH测试

on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: 安装sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        
    - name: SSH密码登录测试
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no qianxi@8.148.186.229 "echo '连接成功'"
