name: Build & Push Nginx
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: aliio8
          password: ${{ secrets.GHCR_TOKEN }}

      - run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/nginx-demo:latest
          docker build -t $IMAGE .
          docker push $IMAGE
